const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  LOADING: "LOADING",
  SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
  SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
  SET_RECENT_SONG: "SET_RECENT_SONG",
  SEARCH: "SEARCH",
  SCROLL: "SCROLL",

  //music
  PLAY: "PLAY",
  PLAYLIST: "PLAYLIST",
};

export default actionTypes;
